[project]
name = "t"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.37",
    "sqlalchemy-continuum>=1.4.2",
]

[dependency-groups]
dev = [
    "ruff>=0.9.3",
]
